version: 0.0
os: linux
files:
  - source: ./direct.jar
    destination: /home/direct/direct_backup/
permissions:
  - object: /home/direct/direct_backup
    pattern: "direct.jar"
    owner: direct
    group: rvm
hooks:
  BeforeInstall:
    - location: remote-cmd-backup-app.sh
      runas: direct
  AfterInstall:
    - location: remote-cmd-expand-app.sh
      runas: direct
    - location: remote-cmd-stop-server.sh
      runas: direct
    - location: remote-cmd-deploy-app.sh 
      runas: direct
  ApplicationStart: 
    - location: remote-cmd-start-server.sh
      runas: direct

