iversion: 2

jobs:
  # Build & Deploy against development backend
  "build-dev":
    docker:
      - image: openjdk:7
    steps:
      # Initialization.
      - run:
          name: Installation of build dependencies.
          command: |
            apt update
            apt install -y  openssl ant git
      - run:
          name: checking out build repo
          command: |
            git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript 
            git clone --branch master https://github.com/appirio-tech/ops ../direct-config-update
      - checkout
      - run:
          name: copying configuration file
          command: |
            cp ./../buildscript/direct/conf/dev/token.properties.enc .
            openssl enc -aes-256-cbc -d -in token.properties.enc -out token.properties -k $SECPASSWD
      - run:
          name: Installation of build dependencies.
          command: |
            javac -version
            ant -version
            ant package-direct package-static-direct
      - run:
          name: Deployment.
          command: |
            cp ./../buildscript/master_deploy.sh .
workflows:
  version: 2
  build:
    jobs:
      - build-dev:
          filters:
            branches:
              only: dev-circleci
